#!/usr/bin/env bash
# Agent / zero-config deploy of projektor.
#
#   PROJEKTOR_REPO=you/projektor ADMIN_EMAILS=you@example.com ./deploy-auto.sh
#
# Unlike ./deploy.sh, this needs NO manual `wrangler d1/kv/r2 create` and NO
# copying of resource IDs. It writes a binding-only wrangler.toml (no IDs) and
# lets wrangler's automatic resource provisioning (>= 4.45) create the D1
# database, KV namespace, and R2 bucket on first `deploy`, writing the IDs back.
#
# This is the path an AI agent takes: "deploy projektor to my Cloudflare account."
#
# Auth: `wrangler login` (local) OR CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID
#       (CI / headless agent). The token needs the same scopes as deploy.sh —
#       Workers Scripts, D1, KV, R2 (Edit) + Account Settings (Read).
#
# Requires: wrangler >= 4.45, gh, bash, tar, openssl.
set -euo pipefail

# ── Config (override via env) ────────────────────────────────────────────────
REPO="${PROJEKTOR_REPO:-REPLACE_WITH_YOUR_GITHUB_USER/projektor}"
WRANGLER="${WRANGLER:-npx wrangler}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

VERSION="${PROJEKTOR_VERSION:-$(cat projektor.version 2>/dev/null || true)}"
: "${VERSION:?Set PROJEKTOR_VERSION or write a tag (e.g. v1.2.0) to ./projektor.version}"
: "${ADMIN_EMAILS:?Set ADMIN_EMAILS (comma-separated owner emails — first to log in owns the default workspace)}"

echo "==> Fetching projektor $VERSION from $REPO"
rm -rf vendor && mkdir -p vendor
TMP="$(mktemp -d)"
gh release download "$VERSION" -R "$REPO" -p 'projektor-*.tar.gz' -D "$TMP"
tar -xzf "$TMP"/projektor-*.tar.gz -C vendor
rm -rf "$TMP"

# ── Generate a binding-only wrangler.toml on first run ───────────────────────
# No resource IDs: wrangler auto-provisions DB/KV/R2 on `deploy` and writes the
# IDs back into this file, so subsequent deploys reuse them. We only create it if
# absent — re-running must not clobber the IDs wrangler wrote back.
if [ ! -f wrangler.toml ]; then
  COMPAT_DATE="$(sed -n 's/^compatibility_date = "\([^"]*\)".*/\1/p' vendor/wrangler.example.toml)"
  : "${COMPAT_DATE:?could not read compatibility_date from vendor/wrangler.example.toml}"

  echo "==> Writing binding-only wrangler.toml (no resource IDs — wrangler will provision)"
  cat > wrangler.toml <<EOF
# Generated by deploy-auto.sh — binding-only config. wrangler provisions the
# D1/KV/R2 resources on first \`deploy\` and writes their IDs back below.
name = "projektor"
main = "./vendor/worker.js"
compatibility_date = "$COMPAT_DATE"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./vendor/web"
binding = "ASSETS"
run_worker_first = ["/api/*", "/mcp/*"]

[[d1_databases]]
binding = "DB"
database_name = "projektor"
migrations_dir = "./vendor/migrations"

[[kv_namespaces]]
binding = "KV"

[[r2_buckets]]
binding = "R2"
bucket_name = "projektor-files"

[vars]
ENVIRONMENT = "production"
ADMIN_EMAILS = "$ADMIN_EMAILS"
DEFAULT_WORKSPACE_SLUG = "projektor"
DEFAULT_WORKSPACE_NAME = "Projektor"
AUTO_JOIN_ROLE = "viewer"
EOF

  # CF Access is only needed for browser login (read at request time, not boot).
  # Include it now if provided; otherwise configure it later and re-deploy.
  if [ -n "${CF_ACCESS_TEAM_DOMAIN:-}" ] && [ -n "${CF_ACCESS_AUDIENCE:-}" ]; then
    cat >> wrangler.toml <<EOF
CF_ACCESS_TEAM_DOMAIN = "$CF_ACCESS_TEAM_DOMAIN"
CF_ACCESS_AUDIENCE = "$CF_ACCESS_AUDIENCE"
EOF
  fi
fi

# ── Deploy (auto-provisions any missing D1/KV/R2, then writes IDs back) ───────
echo "==> Deploying Worker (auto-provisions missing resources)"
$WRANGLER deploy --config wrangler.toml

# ── Apply D1 migrations by BINDING name (works regardless of DB name) ────────
echo "==> Applying D1 migrations (remote)"
$WRANGLER d1 migrations apply DB --remote --config wrangler.toml

# ── Set JWT_SECRET once (persists across deploys) ────────────────────────────
if ! $WRANGLER secret list --config wrangler.toml 2>/dev/null | grep -q '"JWT_SECRET"'; then
  echo "==> Setting JWT_SECRET (generated, set once)"
  openssl rand -hex 32 | $WRANGLER secret put JWT_SECRET --config wrangler.toml
fi

echo ""
echo "==> Deployed projektor $VERSION"
echo "    Resources were auto-provisioned; their IDs are now in ./wrangler.toml"
if [ -z "${CF_ACCESS_TEAM_DOMAIN:-}" ]; then
  echo "    NOTE: CF Access is not configured — browser login will not work until you"
  echo "    set up a Cloudflare Access application and re-run with CF_ACCESS_TEAM_DOMAIN"
  echo "    and CF_ACCESS_AUDIENCE set (or add them to wrangler.toml and re-deploy)."
fi
