#!/usr/bin/env bash
# Agent / zero-config deploy of projektor.
#
#   PROJEKTOR_REPO=you/projektor ADMIN_EMAILS=you@example.com ./deploy-auto.sh
#
# Unlike ./deploy.sh, this needs NO manual `wrangler d1/kv/r2 create` and NO
# resource IDs anywhere. It writes a binding-only wrangler.toml (no IDs) and lets
# wrangler's automatic resource provisioning create the D1 database, KV namespace,
# and R2 bucket on first `deploy`. wrangler then resolves all three by binding /
# name on every command (deploy AND `d1 migrations apply`), so you never paste an
# ID. Verified on wrangler 4.105 (4.66 provisions fine but its `d1 migrations`
# still demands a database_id — hence the version floor below).
#
# This is the path an AI agent takes: "deploy projektor to my Cloudflare account."
#
# Auth: `wrangler login` (local) OR CLOUDFLARE_API_TOKEN + CLOUDFLARE_ACCOUNT_ID
#       (CI / headless agent). The token needs the same scopes as deploy.sh —
#       Workers Scripts, D1, KV, R2 (Edit) + Account Settings (Read).
#
# Requires: wrangler >= 4.103 (this repo pins it), gh, bash, tar, openssl.
set -euo pipefail

# ── Config (override via env) ────────────────────────────────────────────────
REPO="${PROJEKTOR_REPO:-REPLACE_WITH_YOUR_GITHUB_USER/projektor}"
WRANGLER="${WRANGLER:-npx wrangler}"
# Worker + resource name. Override to stand up a second/demo instance on an
# account that already runs projektor (avoids clobbering existing resources).
NAME="${PROJEKTOR_NAME:-projektor}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

VERSION="${PROJEKTOR_VERSION:-$(cat projektor.version 2>/dev/null || true)}"
: "${VERSION:?Set PROJEKTOR_VERSION or write a tag (e.g. v1.2.0) to ./projektor.version}"
: "${ADMIN_EMAILS:?Set ADMIN_EMAILS (comma-separated owner emails — first to log in owns the default workspace)}"

# ── Require a wrangler new enough to provision AND run id-less d1 migrations ──
# Older wranglers (e.g. 4.66) provision the resources but then fail at
# `d1 migrations apply` demanding a database_id, leaving a half-deployed instance.
MIN_WRANGLER="4.103.0"
WRANGLER_VER="$($WRANGLER --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
if [ -n "$WRANGLER_VER" ] && \
   [ "$(printf '%s\n%s\n' "$MIN_WRANGLER" "$WRANGLER_VER" | sort -V | head -1)" != "$MIN_WRANGLER" ]; then
  echo "ERROR: wrangler >= $MIN_WRANGLER required (found $WRANGLER_VER)." >&2
  echo "       Older versions provision resources but cannot apply D1 migrations without an ID." >&2
  exit 1
fi

echo "==> Fetching projektor $VERSION from $REPO"
rm -rf vendor && mkdir -p vendor
TMP="$(mktemp -d)"
gh release download "$VERSION" -R "$REPO" -p 'projektor-*.tar.gz' -D "$TMP"
tar -xzf "$TMP"/projektor-*.tar.gz -C vendor
rm -rf "$TMP"

# ── Generate a binding-only wrangler.toml on first run ───────────────────────
# No resource IDs: wrangler provisions DB/KV/R2 by name on first `deploy` and
# resolves them by binding/name thereafter. We only create the file if absent so
# a re-run preserves any edits you made (e.g. CF Access vars).
if [ ! -f wrangler.toml ]; then
  COMPAT_DATE="$(sed -n 's/^compatibility_date = "\([^"]*\)".*/\1/p' vendor/wrangler.example.toml)"
  : "${COMPAT_DATE:?could not read compatibility_date from vendor/wrangler.example.toml}"

  echo "==> Writing binding-only wrangler.toml (no resource IDs — wrangler will provision)"
  cat > wrangler.toml <<EOF
# Generated by deploy-auto.sh — binding-only config. wrangler provisions the
# D1/KV/R2 resources by name on first \`deploy\` and resolves them by binding
# thereafter; no resource IDs are needed.
name = "$NAME"
main = "./vendor/worker.js"
compatibility_date = "$COMPAT_DATE"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./vendor/web"
binding = "ASSETS"
run_worker_first = ["/api/*", "/mcp/*"]

[[d1_databases]]
binding = "DB"
database_name = "$NAME"
migrations_dir = "./vendor/migrations"

[[kv_namespaces]]
binding = "KV"

[[r2_buckets]]
binding = "R2"
bucket_name = "$NAME-files"

[vars]
ENVIRONMENT = "production"
ADMIN_EMAILS = "$ADMIN_EMAILS"
DEFAULT_WORKSPACE_SLUG = "projektor"
DEFAULT_WORKSPACE_NAME = "Projektor"
# Invite-only by default: only ADMIN_EMAILS become owners; everyone else CF Access
# admits must be invited. To auto-join admitted users instead, add e.g.
#   AUTO_JOIN_ROLE = "viewer"
EOF

  # CF Access is only needed for browser login (read at request time, not boot).
  # Include it now if provided; otherwise configure it later and re-deploy.
  if [ -n "${CF_ACCESS_TEAM_DOMAIN:-}" ] && [ -n "${CF_ACCESS_AUDIENCE:-}" ]; then
    cat >> wrangler.toml <<EOF
CF_ACCESS_TEAM_DOMAIN = "$CF_ACCESS_TEAM_DOMAIN"
CF_ACCESS_AUDIENCE = "$CF_ACCESS_AUDIENCE"
EOF
  fi
fi

# ── Deploy (auto-provisions any missing D1/KV/R2 by name) ────────────────────
echo "==> Deploying Worker (auto-provisions missing resources)"
$WRANGLER deploy --config wrangler.toml

# ── Apply D1 migrations by BINDING name (works regardless of DB name) ────────
echo "==> Applying D1 migrations (remote)"
$WRANGLER d1 migrations apply DB --remote --config wrangler.toml

# ── Set JWT_SECRET once (persists across deploys) ────────────────────────────
if ! $WRANGLER secret list --config wrangler.toml 2>/dev/null | grep -q '"JWT_SECRET"'; then
  echo "==> Setting JWT_SECRET (generated, set once)"
  openssl rand -hex 32 | $WRANGLER secret put JWT_SECRET --config wrangler.toml
fi

echo ""
echo "==> Deployed projektor $VERSION"
echo "    D1/KV/R2 were auto-provisioned by name; no resource IDs were needed."
if [ -z "${CF_ACCESS_TEAM_DOMAIN:-}" ]; then
  echo "    NOTE: CF Access is not configured — browser login will not work until you"
  echo "    set up a Cloudflare Access application and re-run with CF_ACCESS_TEAM_DOMAIN"
  echo "    and CF_ACCESS_AUDIENCE set (or add them to wrangler.toml and re-deploy)."
fi
